import streamlit as st
import pickle
import pandas as pd
import sqlite3
from pathlib import Path
import io

# Visuals & Statistics sathi
import plotly.express as px

# PDF Generation sathi ReportLab
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# -----------------------------
# File Paths
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent

def find_file(filename, folder=None):
    candidates = []
    if folder:
        candidates.append(BASE_DIR / folder / filename)
    candidates.append(BASE_DIR / filename)

    for path in candidates:
        if path.exists():
            return path

    searched = "\n".join(str(p) for p in candidates)
    raise FileNotFoundError(
        f"File not found: {filename}\nChecked:\n{searched}"
    )

st.set_page_config(
    page_title="Smart Hospital Management System",
    page_icon="🏥",
    layout="wide"
)

# -----------------------------
# Advanced PDF Report & Prescription Generator
# -----------------------------
def generate_pdf_report(patient_name, age, gender, phone, symptoms, disease, description, specialist, medicines="", doctor_notes=""):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []

    # Title & Header
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor("#0D3B66"),
        alignment=1,
        spaceAfter=15
    )
    story.append(Paragraph("🏥 SMART HOSPITAL MEDICAL REPORT & PRESCRIPTION", header_style))
    story.append(Spacer(1, 10))

    # Patient Details Section
    story.append(Paragraph("<b>👤 Patient Information</b>", styles['Heading2']))
    patient_data = [
        [Paragraph(f"<b>Name:</b> {patient_name}", styles['Normal']), Paragraph(f"<b>Age/Gender:</b> {age} / {gender}", styles['Normal'])],
        [Paragraph(f"<b>Phone:</b> {phone}", styles['Normal']), Paragraph(f"<b>Date:</b> {pd.Timestamp.now().strftime('%Y-%m-%d')}", styles['Normal'])]
    ]
    t_patient = Table(patient_data, colWidths=[270, 270])
    t_patient.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F0F4F8")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#BCCCDC")),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_patient)
    story.append(Spacer(1, 15))

    # Diagnostic Details
    story.append(Paragraph("<b>🔬 Clinical Prediction & Diagnosis</b>", styles['Heading2']))
    diag_data = [
        [Paragraph("<b>Selected Symptoms:</b>", styles['Normal']), Paragraph(", ".join(symptoms) if isinstance(symptoms, list) else str(symptoms), styles['Normal'])],
        [Paragraph("<b>Predicted Disease:</b>", styles['Normal']), Paragraph(f"<font color='#D90429'><b>{disease}</b></font>", styles['Normal'])],
        [Paragraph("<b>Recommended Specialist:</b>", styles['Normal']), Paragraph(f"<b>{specialist}</b>", styles['Normal'])],
        [Paragraph("<b>Disease Summary:</b>", styles['Normal']), Paragraph(description, styles['Normal'])]
    ]

    t_diag = Table(diag_data, colWidths=[150, 390])
    t_diag.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FFFFFF")),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E0")),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t_diag)
    story.append(Spacer(1, 15))

    # Prescribed Medicines & Notes
    if medicines or doctor_notes:
        story.append(Paragraph("<b>💊 Prescribed Medicines & Doctor Advice</b>", styles['Heading2']))
        rx_data = [
            [Paragraph("<b>Rx / Medicines:</b>", styles['Normal']), Paragraph(medicines if medicines else "As advised by doctor.", styles['Normal'])],
            [Paragraph("<b>Doctor Notes:</b>", styles['Normal']), Paragraph(doctor_notes if doctor_notes else "Rest and follow up after 5 days.", styles['Normal'])]
        ]
        t_rx = Table(rx_data, colWidths=[150, 390])
        t_rx.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FFFBEA")),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#F6AD55")),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(t_rx)
        story.append(Spacer(1, 15))

    # Disclaimer / Footer
    footer_style = ParagraphStyle('FooterStyle', parent=styles['Italic'], fontSize=8, textColor=colors.gray, alignment=1)
    story.append(Paragraph("Note: This is an automated preliminary medical report generated by Smart Hospital AI. Please consult a registered doctor for clinical verification.", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer

# CSV Export Helper
def convert_df_to_csv(df):
    return df.to_csv(index=False).encode('utf-8')

# -----------------------------
# Simple Original Login
# -----------------------------
DEMO_USERNAME = "admin"
DEMO_PASSWORD = "admin123"

if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False

if not st.session_state["logged_in"]:
    st.title("🏥 Smart Hospital Management & Recommendation System")
    st.subheader("🔐 Sign In")
    username = st.text_input("👤 Username")
    password = st.text_input("🔑 Password", type="password")
    if st.button("🚪 Login", use_container_width=True):
        if username == DEMO_USERNAME and password == DEMO_PASSWORD:
            st.session_state["logged_in"] = True
            st.rerun()
        else:
            st.error("Invalid username or password.")
    st.stop()

# -----------------------------
# Load ML Model & Vectorizer
# -----------------------------
with open(find_file("disease_model.pkl", "model"), "rb") as f:
    model = pickle.load(f)

with open(find_file("vectorizer.pkl", "model"), "rb") as f:
    vectorizer = pickle.load(f)

# -----------------------------
# Database Connection
# -----------------------------
conn = sqlite3.connect(
    find_file("hospital.db", "database"),
    check_same_thread=False
)

disease_description = pd.read_csv(find_file("Disease_Description.csv", "data"), encoding="latin1")
disease_description.columns = [col.strip() for col in disease_description.columns]

doctor_disease = pd.read_csv(find_file("Doctor_Versus_Disease.csv", "data"), header=None, names=["Disease", "Specialist"], encoding="latin1")
doctor_disease["Disease"] = doctor_disease["Disease"].astype(str).str.replace("\xa0", " ", regex=False).str.strip()
doctor_disease["Specialist"] = doctor_disease["Specialist"].astype(str).str.replace("\xa0", " ", regex=False).str.strip()

# -----------------------------
# Sidebar Navigation (Original)
# -----------------------------
st.sidebar.title("🏥 Hospital System")

if st.sidebar.button("📙 Logout", use_container_width=True):
    st.session_state["logged_in"] = False
    st.rerun()

st.sidebar.write("Navigation")

menu = st.sidebar.radio(
    "",
    [
        "Dashboard",
        "Disease Prediction",
        "Appointments",
        "Doctors",
        "Patients",
        "Patient History",
        "Analytics",
        "Reports & Feedback"
    ],
    label_visibility="collapsed"
)

# -----------------------------
# Header Display
# -----------------------------
st.title("🏥 Smart Hospital Management & Recommendation System")

# -----------------------------
# 1. Dashboard
# -----------------------------
if menu == "Dashboard":
    st.header("📊 Dashboard")
    
    total_patients = pd.read_sql_query("SELECT COUNT(*) AS count FROM patients", conn).iloc[0]["count"]
    total_doctors = pd.read_sql_query("SELECT COUNT(*) AS count FROM doctors", conn).iloc[0]["count"]
    total_appointments = pd.read_sql_query("SELECT COUNT(*) AS count FROM appointments", conn).iloc[0]["count"]
    pending = pd.read_sql_query("SELECT COUNT(*) AS count FROM appointments WHERE LOWER(status)='pending' OR LOWER(status)='booked'", conn).iloc[0]["count"]

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("👤 Total Patients", total_patients)
    col2.metric("👨‍⚕️ Total Doctors", total_doctors)
    col3.metric("📅 Total Appointments", total_appointments)
    col4.metric("⏳ Pending", pending)

    st.divider()

    st.subheader("🏥 Smart Hospital Management System")
    st.write("Welcome to the Smart Hospital Management & Recommendation System.")

    st.subheader("✨ This System Provides")
    st.write("🔬 **Disease Prediction** — Predict possible disease from selected symptoms.")
    st.write("🩺 **Specialist Recommendation** — Recommend a suitable medical specialist.")
    st.write("👨‍⚕️ **Doctor Information** — View doctors and their duty schedules.")
    st.write("👤 **Patient Management** — Add and manage patient information.")
    st.write("📅 **Appointment Booking** — Book and manage patient appointments.")
    st.write("📜 **Patient History** — View previous patient visit records.")
    st.write("📊 **Analytics** — View hospital statistics and appointment trends.")
    st.write("📑 **Medical Reports** — Generate downloadable patient reports.")

    st.divider()
    st.subheader("📌 Quick Statistics")
    
    app_status_df = pd.read_sql_query("SELECT status, COUNT(*) as count FROM appointments GROUP BY status", conn)
    if not app_status_df.empty:
        fig_quick = px.bar(app_status_df, x='status', y='count', color='status', title="Appointment Status Overview")
        st.plotly_chart(fig_quick, use_container_width=True)
    else:
        st.info("No appointment statistics available yet.")

# -----------------------------
# 2. Disease Prediction
# -----------------------------
elif menu == "Disease Prediction":
    st.header("🔬 Disease Prediction")
    st.write("Select patient and symptoms for disease prediction.")

    patients_df = pd.read_sql_query("SELECT patient_id, patient_name, age, gender, phone FROM patients ORDER BY patient_name", conn)

    if patients_df.empty:
        st.warning("No patients registered. Please add patients first.")
    else:
        patient_map = {row['patient_name']: row for _, row in patients_df.iterrows()}
        selected_patient_name = st.selectbox("👤 Select Patient", list(patient_map.keys()))
        selected_patient_info = patient_map[selected_patient_name]

        st.divider()

        symptom_df = pd.read_csv(find_file("Symptom_Weights.csv", "data"), header=None, names=["Symptom", "Weight"], encoding="latin1")
        symptom_df["Symptom"] = symptom_df["Symptom"].astype(str).str.replace("_", " ", regex=False).str.strip()
        all_symptoms = sorted(symptom_df["Symptom"].unique())

        selected_symptoms = st.multiselect("🩺 Select Symptoms", all_symptoms)

        with st.expander("💊 Add Medicine Prescription & Doctor Notes (Optional)"):
            rx_medicines = st.text_area("Prescribed Medicines (e.g. Paracetamol 500mg, Amoxicillin)", value="")
            rx_notes = st.text_area("Doctor Special Advice", value="Take rest, drink warm water, follow up after 3 days.")

        if st.button("🔍 Predict Disease"):
            if not selected_symptoms:
                st.warning("Please select at least one symptom.")
            else:
                symptom_text = " ".join(selected_symptoms)
                symptom_vector = vectorizer.transform([symptom_text])
                predicted_disease = model.predict(symptom_vector)[0]

                st.success(f"Predicted Disease: **{predicted_disease}**")

                description_row = disease_description[disease_description["Disease"].astype(str).str.strip().str.lower() == predicted_disease.strip().lower()]
                description = description_row.iloc[0]["Description"] if not description_row.empty else "Detailed description not available."

                st.subheader("📋 Disease Description")
                st.info(description)

                specialist_row = doctor_disease[doctor_disease["Disease"].astype(str).str.strip().str.lower() == predicted_disease.strip().lower()]
                specialist = specialist_row.iloc[0]["Specialist"] if not specialist_row.empty else "General Physician"

                st.subheader("🩺 Recommended Specialist")
                st.success(specialist)

                st.session_state["last_prediction"] = {
                    "patient_name": selected_patient_info["patient_name"],
                    "age": selected_patient_info.get("age", "N/A"),
                    "gender": selected_patient_info.get("gender", "N/A"),
                    "phone": selected_patient_info.get("phone", "N/A"),
                    "symptoms": selected_symptoms,
                    "disease": predicted_disease,
                    "description": description,
                    "specialist": specialist,
                    "medicines": rx_medicines,
                    "notes": rx_notes
                }

                st.subheader("👨‍⚕️ Available Doctors")
                available_doctors = pd.read_sql_query(
                    """SELECT d.doctor_name AS Doctor, d.specialization AS Specialist, ds.shift_name AS Shift,
                              ds.start_time AS Start_Time, ds.end_time AS End_Time, d.room_number AS Room
                       FROM doctor_shifts ds JOIN doctors d ON ds.doctor_id = d.doctor_id
                       WHERE LOWER(TRIM(d.specialization)) = LOWER(TRIM(?))""",
                    conn, params=(specialist,)
                )

                if not available_doctors.empty:
                    st.dataframe(available_doctors, use_container_width=True, hide_index=True)
                else:
                    st.info(f"No available {specialist} doctors found for today.")

        if "last_prediction" in st.session_state:
            st.divider()
            pred = st.session_state["last_prediction"]
            pdf_bytes = generate_pdf_report(
                pred["patient_name"], pred["age"], pred["gender"], pred["phone"],
                pred["symptoms"], pred["disease"], pred["description"], pred["specialist"],
                pred.get("medicines", ""), pred.get("notes", "")
            )

            st.download_button(
                label="📥 Download Diagnostic & Prescription PDF Report",
                data=pdf_bytes,
                file_name=f"Medical_Report_{pred['patient_name'].replace(' ', '_')}.pdf",
                mime="application/pdf",
                use_container_width=True
            )

# -----------------------------
# 3. Appointments
# -----------------------------
elif menu == "Appointments":
    st.header("📅 Appointment Booking & Management")
    patients = pd.read_sql_query("SELECT patient_id, patient_name FROM patients", conn)
    doctors = pd.read_sql_query("SELECT doctor_id, doctor_name, specialization FROM doctors", conn)

    if not patients.empty and not doctors.empty:
        patient_options = {f"{row['patient_name']} (ID: {row['patient_id']})": row["patient_id"] for _, row in patients.iterrows()}
        selected_patient = st.selectbox("👤 Select Patient", list(patient_options.keys()))
        selected_patient_id = patient_options[selected_patient]

        doctor_options = {f"{row['doctor_name']} - {row['specialization']}": row["doctor_id"] for _, row in doctors.iterrows()}
        selected_doctor = st.selectbox("👨‍⚕️ Select Doctor", list(doctor_options.keys()))
        selected_doctor_id = doctor_options[selected_doctor]

        appointment_date = st.date_input("📅 Appointment Date")
        appointment_time = st.time_input("⏰ Appointment Time")
        reason = st.text_input("📝 Reason for Appointment")

        if st.button("📅 Book Appointment"):
            cursor = conn.cursor()
            cursor.execute(
                """INSERT INTO appointments (patient_id, doctor_id, appointment_date, appointment_time, status, reason)
                   VALUES (?, ?, ?, ?, ?, ?)""",
                (selected_patient_id, selected_doctor_id, appointment_date.strftime("%Y-%m-%d"), appointment_time.strftime("%H:%M"), "Booked", reason)
            )
            conn.commit()
            st.success(f"Appointment booked successfully!")
            st.rerun()

    st.subheader("📋 Booked Appointments List")
    appointments = pd.read_sql_query(
        """SELECT a.appointment_id, p.patient_name, d.doctor_name, d.specialization, a.appointment_date, a.appointment_time, a.status, a.reason
           FROM appointments a JOIN patients p ON a.patient_id = p.patient_id JOIN doctors d ON a.doctor_id = d.doctor_id ORDER BY a.appointment_id DESC""",
        conn
    )
    st.dataframe(appointments, use_container_width=True, hide_index=True)

    if not appointments.empty:
        st.download_button(
            label="📥 Export Appointments List to CSV",
            data=convert_df_to_csv(appointments),
            file_name="Appointments_List.csv",
            mime="text/csv"
        )

# -----------------------------
# 4. Doctors
# -----------------------------
elif menu == "Doctors":
    st.header("👨‍⚕️ Doctors Directory & Schedules")
    doctors = pd.read_sql_query("SELECT doctor_name, specialization, phone, email, room_number FROM doctors", conn)
    st.dataframe(doctors, use_container_width=True, hide_index=True)

    st.subheader("🕒 Doctor Duty Schedules")
    shifts = pd.read_sql_query(
        """SELECT d.doctor_name, d.specialization, ds.duty_date, ds.shift_name, ds.start_time, ds.end_time, d.room_number, ds.status
           FROM doctor_shifts ds JOIN doctors d ON ds.doctor_id = d.doctor_id ORDER BY ds.duty_date DESC""",
        conn
    )
    st.dataframe(shifts, use_container_width=True, hide_index=True)

# -----------------------------
# 5. Patients
# -----------------------------
elif menu == "Patients":
    st.header("👤 Patient Management")

    with st.expander("➕ Register New Patient"):
        with st.form("add_patient_form", clear_on_submit=True):
            p_name = st.text_input("Patient Full Name*")
            p_age = st.number_input("Age*", min_value=1, max_value=120, value=25)
            p_gender = st.selectbox("Gender*", ["Male", "Female", "Other"])
            p_phone = st.text_input("Phone Number")
            p_address = st.text_area("Address")
            p_symptoms = st.text_input("Initial Symptoms")

            if st.form_submit_button("💾 Save Patient"):
                if p_name:
                    cursor = conn.cursor()
                    cursor.execute(
                        """INSERT INTO patients (patient_name, age, gender, phone, address, symptoms, registration_date)
                           VALUES (?, ?, ?, ?, ?, ?, DATE('now'))""",
                        (p_name, p_age, p_gender, p_phone, p_address, p_symptoms)
                    )
                    conn.commit()
                    st.success(f"Patient '{p_name}' successfully added!")
                    st.rerun()

    st.subheader("📋 Registered Patients Registry")
    
    search_query = st.text_input("🔍 Search Patient by Name or Phone", "")
    patients = pd.read_sql_query("SELECT patient_id, patient_name, age, gender, phone, address, symptoms, registration_date FROM patients ORDER BY patient_id DESC", conn)

    if search_query:
        patients = patients[
            patients["patient_name"].str.contains(search_query, case=False, na=False) |
            patients["phone"].astype(str).str.contains(search_query, case=False, na=False)
        ]

    st.dataframe(patients, use_container_width=True, hide_index=True)

    if not patients.empty:
        st.download_button(
            label="📥 Export Patients Registry to CSV",
            data=convert_df_to_csv(patients),
            file_name="Patients_Registry.csv",
            mime="text/csv"
        )

# -----------------------------
# 6. Patient History
# -----------------------------
elif menu == "Patient History":
    st.header("📜 Patient History")
    history = pd.read_sql_query(
        """SELECT ph.history_id AS "History ID", p.patient_name AS "Patient Name", d.doctor_name AS "Doctor Name",
           ph.visit_date AS "Visit Date", ph.department AS "Department", ph.symptoms AS "Symptoms", ph.notes AS "Notes"
           FROM patient_history ph LEFT JOIN patients p ON ph.patient_id = p.patient_id LEFT JOIN doctors d ON ph.doctor_id = d.doctor_id ORDER BY ph.visit_date DESC""",
        conn
    )
    st.dataframe(history, use_container_width=True, hide_index=True)

# -----------------------------
# 7. Analytics
# -----------------------------
elif menu == "Analytics":
    st.header("📈 Interactive Hospital Visual Analytics")

    col1, col2 = st.columns(2)

    with col1:
        doctors_df = pd.read_sql_query("SELECT specialization, COUNT(*) as count FROM doctors GROUP BY specialization", conn)
        if not doctors_df.empty:
            fig1 = px.pie(doctors_df, values='count', names='specialization', title="👨‍⚕️ Doctors Specialization Distribution", hole=0.4)
            st.plotly_chart(fig1, use_container_width=True)

    with col2:
        patients_df = pd.read_sql_query("SELECT age, gender FROM patients", conn)
        if not patients_df.empty:
            fig2 = px.histogram(patients_df, x="age", color="gender", title="👥 Patient Age & Gender Demographics", nbins=10)
            st.plotly_chart(fig2, use_container_width=True)

    st.subheader("🕒 Doctor Shift Allocations")
    shifts_df = pd.read_sql_query("SELECT shift_name, COUNT(*) as count FROM doctor_shifts GROUP BY shift_name", conn)
    if not shifts_df.empty:
        fig3 = px.bar(shifts_df, x='shift_name', y='count', color='shift_name', title="Doctor Duty Shift Distribution")
        st.plotly_chart(fig3, use_container_width=True)

# -----------------------------
# 8. Reports & Feedback
# -----------------------------
elif menu == "Reports & Feedback":
    st.header("📑 Reports & Patient Feedback")

    st.subheader("📄 Medical PDF Report Generator")
    patients_df = pd.read_sql_query("SELECT patient_id, patient_name, age, gender, phone, symptoms FROM patients ORDER BY patient_name", conn)

    if not patients_df.empty:
        selected_p = st.selectbox("Select Patient to Generate PDF Report", patients_df["patient_name"].tolist())
        p_row = patients_df[patients_df["patient_name"] == selected_p].iloc[0]

        rep_disease = st.text_input("Diagnosed Disease", value="General Checkup / Undefined")
        rep_specialist = st.text_input("Specialist Recommended", value="General Physician")
        rep_meds = st.text_area("Prescribed Medicines", value="Tablet Paracetamol 500mg - Twice daily")
        rep_desc = st.text_area("Doctor Notes / Summary", value="Patient requested full medical evaluation report.")

        pdf_data = generate_pdf_report(
            p_row["patient_name"], p_row.get("age", "N/A"), p_row.get("gender", "N/A"),
            p_row.get("phone", "N/A"), p_row.get("symptoms", "None"), rep_disease, rep_desc, rep_specialist, rep_meds, rep_desc
        )

        st.download_button(
            label="📥 Download Detailed Patient PDF Report",
            data=pdf_data,
            file_name=f"Report_{p_row['patient_name'].replace(' ', '_')}.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    st.divider()
    st.subheader("⭐ Patient Feedback Collection")
    fb_patient = st.text_input("Patient Name (Optional)")
    fb_rating = st.slider("Hospital Experience Rating", 1, 5, 5)
    fb_comments = st.text_area("Feedback Comments")

    if st.button("💬 Submit Feedback"):
        st.success("Thank you! Feedback recorded successfully.")
