import streamlit as st
import pickle
import pandas as pd
import sqlite3
from pathlib import Path
import io

# Visuals & Statistics साठी
import plotly.express as px

# PDF जनरेशनसाठी ReportLab
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# -----------------------------
# File Paths
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent

def find_file(filename, folder=None):
    candidates = []
    if folder:
        candidates.append(BASE_DIR / folder / filename)
    candidates.append(BASE_DIR / filename)

    for path in candidates:
        if path.exists():
            return path

    searched = "\n".join(str(p) for p in candidates)
    raise FileNotFoundError(
        f"File not found: {filename}\nChecked:\n{searched}"
    )

st.set_page_config(
    page_title="Smart Hospital Management System",
    page_icon="🏥",
    layout="wide"
)

# -----------------------------
# Advanced PDF Report Generator
# -----------------------------
def generate_pdf_report(patient_name, age, gender, phone, symptoms, disease, description, specialist):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []

    # Title & Header
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Heading1'],
        fontSize=22,
        textColor=colors.HexColor("#0D3B66"),
        alignment=1,
        spaceAfter=15
    )
    story.append(Paragraph("🏥 SMART HOSPITAL MEDICAL REPORT", header_style))
    story.append(Spacer(1, 10))

    # Patient Details Section
    story.append(Paragraph("<b>👤 Patient Information</b>", styles['Heading2']))
    patient_data = [
        [Paragraph(f"<b>Name:</b> {patient_name}", styles['Normal']), Paragraph(f"<b>Age/Gender:</b> {age} / {gender}", styles['Normal'])],
        [Paragraph(f"<b>Phone:</b> {phone}", styles['Normal']), Paragraph(f"<b>Date:</b> {pd.Timestamp.now().strftime('%Y-%m-%d')}", styles['Normal'])]
    ]
    t_patient = Table(patient_data, colWidths=[270, 270])
    t_patient.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F0F4F8")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#BCCCDC")),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_patient)
    story.append(Spacer(1, 15))

    # Diagnostic Details
    story.append(Paragraph("<b>🔬 Clinical Prediction & Diagnosis</b>", styles['Heading2']))
    diag_data = [
        [Paragraph("<b>Selected Symptoms:</b>", styles['Normal']), Paragraph(", ".join(symptoms), styles['Normal'])],
        [Paragraph("<b>Predicted Disease:</b>", styles['Normal']), Paragraph(f"<font color='#D90429'><b>{disease}</b></font>", styles['Normal'])],
        [Paragraph("<b>Recommended Specialist:</b>", styles['Normal']), Paragraph(f"<b>{specialist}</b>", styles['Normal'])],
        [Paragraph("<b>Disease Summary:</b>", styles['Normal']), Paragraph(description, styles['Normal'])]
    ]

    t_diag = Table(diag_data, colWidths=[150, 390])
    t_diag.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FFFFFF")),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E0")),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t_diag)
    story.append(Spacer(1, 20))

    # Disclaimer / Footer
    footer_style = ParagraphStyle('FooterStyle', parent=styles['Italic'], fontSize=8, textColor=colors.gray, alignment=1)
    story.append(Paragraph("Note: This is an automated preliminary medical report generated by Smart Hospital AI. Please consult a registered doctor for clinical verification.", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer


# -----------------------------
# Professional Login Page
# -----------------------------
DEMO_USERNAME = "admin"
DEMO_PASSWORD = "admin123"

if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False

if not st.session_state["logged_in"]:
    st.markdown(
        """
        <style>
        .login-title { text-align: center; font-size: 34px; font-weight: 700; margin-top: 35px; margin-bottom: 5px; }
        .login-subtitle { text-align: center; font-size: 16px; margin-bottom: 25px; }
        .login-card { padding: 25px; border-radius: 15px; border: 1px solid #d9e2ec; background: #f8fbff; box-shadow: 0 4px 18px rgba(0,0,0,0.08); }
        </style>
        """,
        unsafe_allow_html=True
    )

    st.markdown('<div class="login-title">🏥 Smart Hospital Management System</div>', unsafe_allow_html=True)
    st.markdown('<div class="login-subtitle">Secure Hospital Management & Recommendation Portal</div>', unsafe_allow_html=True)

    left, center, right = st.columns([1, 1.35, 1])
    with center:
        st.markdown('<div class="login-card">', unsafe_allow_html=True)
        st.subheader("🔐 Sign In")
        username = st.text_input("👤 Username", placeholder="Enter username")
        password = st.text_input("🔑 Password", type="password", placeholder="Enter password")
        login_button = st.button("🚪 Login", use_container_width=True)

        if login_button:
            if username == DEMO_USERNAME and password == DEMO_PASSWORD:
                st.session_state["logged_in"] = True
                st.rerun()
            else:
                st.error("Invalid username or password.")

        st.markdown("---")
        st.caption("Demo Login -> Username: admin | Password: admin123")
        st.markdown("</div>", unsafe_allow_html=True)

    st.stop()

# -----------------------------
# Load ML Model & Vectorizer
# -----------------------------
with open(find_file("disease_model.pkl", "model"), "rb") as f:
    model = pickle.load(f)

with open(find_file("vectorizer.pkl", "model"), "rb") as f:
    vectorizer = pickle.load(f)

# -----------------------------
# Database Connection
# -----------------------------
conn = sqlite3.connect(
    find_file("hospital.db", "database"),
    check_same_thread=False
)

# Load Datasets
disease_description = pd.read_csv(find_file("Disease_Description.csv", "data"), encoding="latin1")
disease_description.columns = [col.strip() for col in disease_description.columns]

doctor_disease = pd.read_csv(find_file("Doctor_Versus_Disease.csv", "data"), header=None, names=["Disease", "Specialist"], encoding="latin1")
doctor_disease["Disease"] = doctor_disease["Disease"].astype(str).str.replace("\xa0", " ", regex=False).str.strip()
doctor_disease["Specialist"] = doctor_disease["Specialist"].astype(str).str.replace("\xa0", " ", regex=False).str.strip()


# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.title("🏥 Hospital System")
st.sidebar.success("🟢 Logged in as: Admin")

if st.sidebar.button("🚪 Logout", use_container_width=True):
    st.session_state["logged_in"] = False
    st.rerun()

st.sidebar.divider()

menu = st.sidebar.radio(
    "Navigation",
    ["Dashboard & Analytics", "Disease Prediction", "Appointments", "Doctors", "Patients", "Patient History"]
)

# -----------------------------
# Dashboard & Visual Analytics (New Feature)
# -----------------------------
if menu == "Dashboard & Analytics":
    st.title("📊 Hospital Analytics & Overview")

    total_patients = pd.read_sql_query("SELECT COUNT(*) AS count FROM patients", conn).iloc[0]["count"]
    total_doctors = pd.read_sql_query("SELECT COUNT(*) AS count FROM doctors", conn).iloc[0]["count"]
    total_appointments = pd.read_sql_query("SELECT COUNT(*) AS count FROM appointments", conn).iloc[0]["count"]

    col1, col2, col3 = st.columns(3)
    col1.metric("👤 Total Patients Registered", total_patients)
    col2.metric("👨‍⚕️ Available Doctors", total_doctors)
    col3.metric("📅 Total Appointments Booked", total_appointments)

    st.divider()

    st.subheader("📈 System Visual Statistics")

    col_chart1, col_chart2 = st.columns(2)

    with col_chart1:
        # Doctors Specialization Distribution Chart
        doctors_df = pd.read_sql_query("SELECT specialization, COUNT(*) as count FROM doctors GROUP BY specialization", conn)
        if not doctors_df.empty:
            fig1 = px.pie(doctors_df, values='count', names='specialization', title="👨‍⚕️ Doctors Specialization Distribution", hole=0.4)
            st.plotly_chart(fig1, use_container_width=True)
        else:
            st.info("No doctor specialization data available.")

    with col_chart2:
        # Patient Age Distribution
        patients_df = pd.read_sql_query("SELECT age, gender FROM patients", conn)
        if not patients_df.empty:
            fig2 = px.histogram(patients_df, x="age", color="gender", title="👥 Patient Age Demographics", nbins=10)
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("No patient demographics data available.")

    # Doctor Shifts Overview
    st.subheader("🕒 Doctor Duty Shift Allocation")
    shifts_df = pd.read_sql_query("SELECT shift_name, COUNT(*) as count FROM doctor_shifts GROUP BY shift_name", conn)
    if not shifts_df.empty:
        fig3 = px.bar(shifts_df, x='shift_name', y='count', color='shift_name', title="Shift-wise Doctor Allocation")
        st.plotly_chart(fig3, use_container_width=True)

# -----------------------------
# Appointments
# -----------------------------
elif menu == "Appointments":
    st.header("📅 Appointment Management")
    patients = pd.read_sql_query("SELECT patient_id, patient_name FROM patients", conn)
    doctors = pd.read_sql_query("SELECT doctor_id, doctor_name, specialization FROM doctors", conn)

    if not patients.empty and not doctors.empty:
        patient_options = {f"{row['patient_name']} (ID: {row['patient_id']})": row["patient_id"] for _, row in patients.iterrows()}
        selected_patient = st.selectbox("👤 Select Patient", list(patient_options.keys()), key="appointment_patient")
        selected_patient_id = patient_options[selected_patient]

        doctor_options = {f"{row['doctor_name']} - {row['specialization']}": row["doctor_id"] for _, row in doctors.iterrows()}
        selected_doctor = st.selectbox("👨‍⚕️ Select Doctor", list(doctor_options.keys()), key="appointment_doctor")
        selected_doctor_id = doctor_options[selected_doctor]

        appointment_date = st.date_input("📅 Appointment Date", key="appointment_date")
        appointment_time = st.time_input("⏰ Appointment Time", key="appointment_time")
        reason = st.text_input("📝 Reason for Appointment", key="appointment_reason")

        if st.button("📅 Book Appointment", use_container_width=True, key="book_appointment"):
            cursor = conn.cursor()
            cursor.execute(
                """INSERT INTO appointments (patient_id, doctor_id, appointment_date, appointment_time, status, reason)
                   VALUES (?, ?, ?, ?, ?, ?)""",
                (selected_patient_id, selected_doctor_id, appointment_date.strftime("%Y-%m-%d"), appointment_time.strftime("%H:%M"), "Booked", reason)
            )
            conn.commit()
            st.success(f"Appointment booked successfully! ID: {cursor.lastrowid}")
    else:
        st.warning("Please ensure patients and doctors exist in system.")

    st.subheader("📋 Booked Appointments List")
    appointments = pd.read_sql_query(
        """SELECT a.appointment_id, p.patient_name, d.doctor_name, d.specialization, a.appointment_date, a.appointment_time, a.status, a.reason
           FROM appointments a JOIN patients p ON a.patient_id = p.patient_id JOIN doctors d ON a.doctor_id = d.doctor_id ORDER BY a.appointment_id DESC""",
        conn
    )
    st.dataframe(appointments, use_container_width=True, hide_index=True)

# -----------------------------
# Doctors
# -----------------------------
elif menu == "Doctors":
    st.header("👨‍⚕️ Doctors Directory & Shifts")
    doctors = pd.read_sql_query("SELECT doctor_name, specialization, phone, email, room_number FROM doctors", conn)
    st.dataframe(doctors, use_container_width=True, hide_index=True)

    st.subheader("🕒 Doctor Duty Schedule")
    shifts = pd.read_sql_query(
        """SELECT d.doctor_name, d.specialization, ds.duty_date, ds.shift_name, ds.start_time, ds.end_time, d.room_number, ds.status
           FROM doctor_shifts ds JOIN doctors d ON ds.doctor_id = d.doctor_id ORDER BY ds.duty_date DESC""",
        conn
    )
    st.dataframe(shifts, use_container_width=True, hide_index=True)

# -----------------------------
# Patients (With Add Patient Feature)
# -----------------------------
elif menu == "Patients":
    st.header("👤 Patient Management")

    with st.expander("➕ Register New Patient"):
        with st.form("add_patient_form", clear_on_submit=True):
            col1, col2 = st.columns(2)
            with col1:
                p_name = st.text_input("Patient Full Name*")
                p_age = st.number_input("Age*", min_value=1, max_value=120, value=25)
                p_gender = st.selectbox("Gender*", ["Male", "Female", "Other"])
            with col2:
                p_phone = st.text_input("Phone Number")
                p_address = st.text_area("Address")
                p_symptoms = st.text_input("Initial Symptoms / Complaints")

            submit_patient = st.form_submit_button("💾 Register Patient")

            if submit_patient:
                if not p_name:
                    st.error("Patient Name is required!")
                else:
                    cursor = conn.cursor()
                    cursor.execute(
                        """INSERT INTO patients (patient_name, age, gender, phone, address, symptoms, registration_date)
                           VALUES (?, ?, ?, ?, ?, ?, DATE('now'))""",
                        (p_name, p_age, p_gender, p_phone, p_address, p_symptoms)
                    )
                    conn.commit()
                    st.success(f"Patient '{p_name}' successfully registered!")
                    st.rerun()

    st.subheader("📋 Registered Patient Registry")
    patients = pd.read_sql_query("SELECT patient_id, patient_name, age, gender, phone, address, symptoms, registration_date FROM patients ORDER BY patient_id DESC", conn)
    st.dataframe(patients, use_container_width=True, hide_index=True)

# -----------------------------
# Patient History
# -----------------------------
elif menu == "Patient History":
    st.header("📜 Patient Medical History")
    history = pd.read_sql_query(
        """SELECT ph.history_id AS "History ID", p.patient_name AS "Patient Name", d.doctor_name AS "Doctor Name",
           ph.visit_date AS "Visit Date", ph.department AS "Department", ph.symptoms AS "Symptoms", ph.notes AS "Notes"
           FROM patient_history ph LEFT JOIN patients p ON ph.patient_id = p.patient_id LEFT JOIN doctors d ON ph.doctor_id = d.doctor_id ORDER BY ph.visit_date DESC""",
        conn
    )
    if history.empty:
        st.info("No patient history found.")
    else:
        st.dataframe(history, use_container_width=True, hide_index=True)

# -----------------------------
# Disease Prediction & PDF Generation
# -----------------------------
elif menu == "Disease Prediction":
    st.title("🔬 AI Disease Prediction & Specialist Recommendation")

    patients_df = pd.read_sql_query("SELECT patient_id, patient_name, age, gender, phone FROM patients ORDER BY patient_name", conn)

    if patients_df.empty:
        st.warning("No patients registered. Please register a patient in 'Patients' section first.")
    else:
        # Patient Selection
        patient_map = {row['patient_name']: row for _, row in patients_df.iterrows()}
        selected_patient_name = st.selectbox("👤 Select Patient", list(patient_map.keys()), key="disease_prediction_patient")
        selected_patient_info = patient_map[selected_patient_name]

        st.divider()

        # Symptoms Selection
        symptom_df = pd.read_csv(find_file("Symptom_Weights.csv", "data"), header=None, names=["Symptom", "Weight"], encoding="latin1")
        symptom_df["Symptom"] = symptom_df["Symptom"].astype(str).str.replace("_", " ", regex=False).str.strip()
        all_symptoms = sorted(symptom_df["Symptom"].unique())

        selected_symptoms = st.multiselect("🩺 Select Clinical Symptoms", all_symptoms, key="disease_prediction_symptoms")

        if st.button("🔍 Run Diagnostic Prediction", use_container_width=True, key="predict_disease_button"):
            if len(selected_symptoms) == 0:
                st.warning("Please select at least one symptom.")
            else:
                symptom_text = " ".join(selected_symptoms)
                symptom_vector = vectorizer.transform([symptom_text])
                predicted_disease = model.predict(symptom_vector)[0]

                st.success(f"Predicted Diagnosis: **{predicted_disease}**")

                # Description
                description_row = disease_description[disease_description["Disease"].astype(str).str.strip().str.lower() == predicted_disease.strip().lower()]
                description = description_row.iloc[0]["Description"] if not description_row.empty else "Detailed description not available."

                st.subheader("📋 Disease Overview")
                st.info(description)

                # Specialist Recommendation
                specialist_row = doctor_disease[doctor_disease["Disease"].astype(str).str.strip().str.lower() == predicted_disease.strip().lower()]
                specialist = specialist_row.iloc[0]["Specialist"] if not specialist_row.empty else "General Physician"

                st.subheader("🩺 Recommended Specialist")
                st.success(specialist)

                # Save session state for PDF Download
                st.session_state["last_prediction"] = {
                    "patient_name": selected_patient_info["patient_name"],
                    "age": selected_patient_info["age"],
                    "gender": selected_patient_info["gender"],
                    "phone": selected_patient_info["phone"],
                    "symptoms": selected_symptoms,
                    "disease": predicted_disease,
                    "description": description,
                    "specialist": specialist
                }

                # Available Doctors Table
                st.subheader("👨‍⚕️ On-Duty Specialist Doctors")
                duty_date = st.date_input("📅 Check Availability Date", value=pd.to_datetime("2026-08-24").date(), key="doctor_availability_date")
                duty_date_str = duty_date.strftime("%Y-%m-%d")

                available_doctors = pd.read_sql_query(
                    """SELECT d.doctor_name AS Doctor, d.specialization AS Specialist, ds.shift_name AS Shift,
                              ds.start_time AS Start_Time, ds.end_time AS End_Time, d.room_number AS Room, ds.status AS Status
                       FROM doctor_shifts ds JOIN doctors d ON ds.doctor_id = d.doctor_id
                       WHERE LOWER(TRIM(d.specialization)) = LOWER(TRIM(?)) AND ds.duty_date = ? AND LOWER(TRIM(ds.status)) = 'available'""",
                    conn, params=(specialist, duty_date_str)
                )

                if not available_doctors.empty:
                    st.dataframe(available_doctors, use_container_width=True, hide_index=True)
                else:
                    st.info(f"No available {specialist} doctors on duty for {duty_date_str}.")

        # PDF Download Section
        if "last_prediction" in st.session_state:
            st.divider()
            st.subheader("📄 Generate & Download Patient Medical Report")
            pred = st.session_state["last_prediction"]
            
            pdf_bytes = generate_pdf_report(
                pred["patient_name"],
                pred["age"],
                pred["gender"],
                pred["phone"],
                pred["symptoms"],
                pred["disease"],
                pred["description"],
                pred["specialist"]
            )

            st.download_button(
                label="📥 Download Diagnostic PDF Report",
                data=pdf_bytes,
                file_name=f"Medical_Report_{pred['patient_name'].replace(' ', '_')}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
